image: docker:18

stages:
  - build
  - deploy

before_script:
  - docker info

build-app:
  stage: build
  script:
    - docker build -t python-103:latest .

deploy-app:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml
  only: manual