image: python:3.7.3

stages:
  - build
  - test
  - deploy

before_script:
  - python -V               # Print out python version for debugging

branch-build:
  only:
    - branches
  stage: build
  script: 
  - python app.py

master-build:
  only:
    - master
  stage: build
  script:
    - echo Hello master-build

master-deploy:
  when: manual
  only:
    - master
  stage: deploy
  script:
    - echo Hello master-deploy