image: python:latest

stages:
  - build
  - test
  - deploy

before_script:
  - python -V               # Print out python version for debugging

master-build:
  only:
    - master
  stage: build
  script:
    - print("Hello master-build")

branch-build:
  only:
    - branches
  stage: build
  script: 
  - print("Hello branch-build")

master-deploy:
  only:
    - master
  script:
  - print("Hello master-deploy")