image: docker:18

stages:
  - build
  - test
  - deploy

before_script:
  - docker info

build-app:
  stage: build
  script:
    - docker build -t python-103:latest .

test-app:
  stage: test
  script:
    - echo "This is a test."

deploy-app:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml python-103-stack
  when: manual