image: docker:18

variables:
  REGISTRY: registry.excite.co.id:15000

stages:
  - build
  - test
  - deploy

before_script:
  - docker info

build-app:
  stage: build
  script:
    - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME .
    - docker image tag $CI_PROJECT_NAME:$CI_COMMIT_REF_NAME $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME

test-app:
  stage: test
  script:
    - echo "This is a test."

deploy-app:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml python-103-stack
  when: manual