image: python:latest

stages:
  - build
  - test
  - deploy

before_script:
  - python -V               # Print out python version for debugging

master-build:
  only:
    - master
  stage: build
  script:
    - echo Hello master-build

branch-build:
  only:
    - branches
  stage: build
  script: 
  - echo Hello branch-build

master-deploy:
  only:
    - master
  script:
    - echo Hello master-deploy